version: '3'
services:
  database:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - default

  server:
    build:
      context: ./Account-Service-Server
    ports:
      - 9000:9000
    depends_on:
      - database
    env_file:
      - ./Account-Service-Server/.env
    networks:
      - default

  website:
    build:
      context: ./Account-Service-Website
    ports:
      - 9001:80
    depends_on:
      - server
    networks:
      - default

networks:
  default:
    driver: bridge